/*
 * Descripción: Ventana para ver información de una factura
 * Fecha: 27 de Junio 2022
 * Nombre de integrantes:
 *  - Elizabeth Ramírez Lizárraga
 *  - Alessandra Ramírez Lizárraga
 *  - Elvira Josselin Estrada Lizárraga
 *  - Daniel Andrés Cardenas Alarcón
 *  - Jorge Luis Carrillo Cuevas
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author luis-
 */
public class ventanaVerFacturas extends javax.swing.JFrame {

    /**
     * Creates new form ventanaInicio
     */
    public ventanaVerFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        barraSup = new javax.swing.JPanel();
        jPanel3 = new FondoPanel();
        jPanel4 = new FondoUsuario();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new FondoInicioSesion();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jPanel22 = new IconoProductos();
        jButton8 = new javax.swing.JButton();
        jPanel24 = new IconoEmpleados();
        jPanel25 = new IconoProveedores();
        jPanel26 = new IconoCaja();
        jPanel28 = new IconoReporte();
        jPanel29 = new IconoCerrarSesion();
        jPanel21 = new IconoInicio();
        jButton9 = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jPanel37 = new IconoFacturas();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jPanel40 = new IconoFacturas();
        jPanel23 = new IconoClientes();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel27 = new IconoFacturas();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblCalleProveedor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVolverClientes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblColoniaProveedor = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblNumeroProveedor = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblCiudadCliente = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblEstadoCliente = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lblCodigoCliente = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lblCiudad3 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lbl29 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lblidEmpleado1 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lblidEmpleado2 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lblCiudad10 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lblCiudad1 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lblidEmpleado3 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lblidEmpleado4 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lblidEmpleado5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jPanel49 = new IconoFacturas();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jPanel52 = new IconoFacturas();
        lbl28 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jPanel55 = new IconoFacturas();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jPanel58 = new IconoFacturas();
        lbl33 = new javax.swing.JLabel();
        lbl34 = new javax.swing.JLabel();
        lbl35 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jPanel31 = new IconoFacturas();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jPanel34 = new IconoFacturas();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jPanel43 = new IconoFacturas();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jPanel46 = new IconoFacturas();
        lbl25 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();

        lbl16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl16.setText("Número:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tedemaz | Ver factura");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraSup.setBackground(new java.awt.Color(255, 255, 255));
        barraSup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        barraSup.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 50));
        barraSup.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 50));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel15.setText("Melissa Garza");
        barraSup.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(119, 119, 119));
        jLabel16.setText("25 Junio 2022");
        barraSup.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jPanel1.add(barraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 70));

        jPanel2.setBackground(new java.awt.Color(38, 18, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(38, 18, 137));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Proveedores");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 60));

        jButton4.setBackground(new java.awt.Color(38, 18, 137));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Caja");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 60));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 180, 10));

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Cerrar sesión");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 499, 200, 60));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 20, 20));

        jButton8.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Productos");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 60));

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 20, 20));
        jPanel2.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 20, 20));
        jPanel2.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 20, 20));
        jPanel2.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 20, 20));
        jPanel2.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 20, 20));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jButton9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Inicio");
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        jPanel35.setBackground(new java.awt.Color(34, 19, 101));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel36.setBackground(new java.awt.Color(34, 19, 101));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setBackground(new java.awt.Color(38, 18, 137));
        jButton13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Facturas");
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel36.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel36.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel35.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel38.setBackground(new java.awt.Color(34, 19, 101));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel39.setBackground(new java.awt.Color(34, 19, 101));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(38, 18, 137));
        jButton14.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Facturas");
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel39.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel39.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel38.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel35.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel35.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jButton1.setBackground(new java.awt.Color(38, 18, 137));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clientes");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel35.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        jPanel2.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 60));

        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Reporte");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 60));
        jPanel2.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 20, 20));

        jButton5.setBackground(new java.awt.Color(38, 18, 137));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Facturas");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jButton2.setBackground(new java.awt.Color(38, 18, 137));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Empleados");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 570));

        lblCalleProveedor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCalleProveedor.setText("Andador Palomas");
        jPanel1.add(lblCalleProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("|   Facturas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 22, 130));
        jLabel4.setText("Información de factura");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        btnVolverClientes.setBackground(new java.awt.Color(181, 194, 254));
        btnVolverClientes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnVolverClientes.setForeground(new java.awt.Color(21, 8, 79));
        btnVolverClientes.setText("Volver a Facturas");
        btnVolverClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 190, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Dirección");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        lbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl.setText("Calle:");
        jPanel1.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        lblColoniaProveedor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblColoniaProveedor.setText("Infonavit Alarcón");
        jPanel1.add(lblColoniaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        lbl1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl1.setText("Colonia:");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        lbl2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl2.setText("Número:");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        lblNumeroProveedor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNumeroProveedor.setText("321");
        jPanel1.add(lblNumeroProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        lbl3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl3.setText("Ciudad:");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        lblCiudadCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCiudadCliente.setText("Mazatlán");
        jPanel1.add(lblCiudadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        lbl4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl4.setText("Estado:");
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, -1, -1));

        lblEstadoCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblEstadoCliente.setText("Sinaloa");
        jPanel1.add(lblEstadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, -1, -1));

        lbl5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl5.setText("CP:");
        jPanel1.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, -1, -1));

        lblCodigoCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCodigoCliente.setText("82132");
        jPanel1.add(lblCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, -1, -1));

        lbl15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl15.setForeground(new java.awt.Color(0, 0, 102));
        lbl15.setText("Facturar a");
        jPanel1.add(lbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        lblCiudad3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCiudad3.setText("6692727998");
        jPanel1.add(lblCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        lbl19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl19.setText("Número:");
        jPanel1.add(lbl19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 690, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 760, 490, 10));

        lbl29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl29.setText("Teléfonos");
        jPanel1.add(lbl29, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 770, -1, -1));

        lbl7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl7.setText("Método de pago:");
        jPanel1.add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, -1));

        lblidEmpleado1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblidEmpleado1.setText("Efectivo");
        jPanel1.add(lblidEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, -1, -1));

        lbl8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl8.setText("Nombre:");
        jPanel1.add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        lblidEmpleado2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblidEmpleado2.setText("Alessandra Ramírez Lizárraga");
        jPanel1.add(lblidEmpleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        lbl31.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl31.setText("Teléfono: ");
        jPanel1.add(lbl31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        lblCiudad10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCiudad10.setText("6692727998");
        jPanel1.add(lblCiudad10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        lbl17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl17.setText("Correo:");
        jPanel1.add(lbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        lblCiudad1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCiudad1.setText("silvanaDistribuidora@gmail.com");
        jPanel1.add(lblCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        lbl9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl9.setText("ID:");
        jPanel1.add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        lblidEmpleado3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblidEmpleado3.setText("00012");
        jPanel1.add(lblidEmpleado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        lbl10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl10.setText("Fecha:");
        jPanel1.add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        lblidEmpleado4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblidEmpleado4.setText("09/07/20");
        jPanel1.add(lblidEmpleado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        lbl11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl11.setText("ID. del cliente:");
        jPanel1.add(lbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        lblidEmpleado5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblidEmpleado5.setText("72003");
        jPanel1.add(lblidEmpleado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"4", "Tela metalizada", "Tela metalizada color verde", "34", null},
                {"3", "Resorte", "Resorte para muebles", "150", null},
                {"7", "Tela opaca", "Tela color gris de 150cm", "22", null},
                {"9", "Espuma", "Espuma para autos", null, null}
            },
            new String [] {
                "ID", "Nombre del producto", "Descripción", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblFacturas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 700, 90));

        jPanel47.setBackground(new java.awt.Color(181, 194, 254));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel48.setBackground(new java.awt.Color(34, 19, 101));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setBackground(new java.awt.Color(38, 18, 137));
        jButton17.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Facturas");
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel48.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel48.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel47.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel50.setBackground(new java.awt.Color(34, 19, 101));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel51.setBackground(new java.awt.Color(34, 19, 101));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton18.setBackground(new java.awt.Color(38, 18, 137));
        jButton18.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Facturas");
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel51.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel51.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel50.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel47.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        lbl28.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl28.setText("78,500.00");
        jPanel47.add(lbl28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lbl30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl30.setText("70,000.00");
        jPanel47.add(lbl30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl32.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl32.setText("8,500.00");
        jPanel47.add(lbl32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jPanel53.setBackground(new java.awt.Color(181, 194, 254));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel54.setBackground(new java.awt.Color(34, 19, 101));
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setBackground(new java.awt.Color(38, 18, 137));
        jButton19.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Facturas");
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel54.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel54.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel53.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel56.setBackground(new java.awt.Color(34, 19, 101));
        jPanel56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel57.setBackground(new java.awt.Color(34, 19, 101));
        jPanel57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton20.setBackground(new java.awt.Color(38, 18, 137));
        jButton20.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Facturas");
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel57.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel57.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel56.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel53.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        lbl33.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl33.setText("Total");
        jPanel53.add(lbl33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lbl34.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl34.setText("Subtotal");
        jPanel53.add(lbl34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl35.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl35.setText("IVA");
        jPanel53.add(lbl35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jPanel47.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 130, 120));

        jPanel1.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 130, 120));

        jPanel20.setBackground(new java.awt.Color(230, 230, 230));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel30.setBackground(new java.awt.Color(34, 19, 101));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(new java.awt.Color(38, 18, 137));
        jButton11.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Facturas");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel30.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel20.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel32.setBackground(new java.awt.Color(34, 19, 101));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBackground(new java.awt.Color(34, 19, 101));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setBackground(new java.awt.Color(38, 18, 137));
        jButton12.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Facturas");
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel33.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel33.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel20.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        lbl22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl22.setText("Total");
        jPanel20.add(lbl22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lbl23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl23.setText("Subtotal");
        jPanel20.add(lbl23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl24.setText("IVA");
        jPanel20.add(lbl24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jPanel41.setBackground(new java.awt.Color(181, 194, 254));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel42.setBackground(new java.awt.Color(34, 19, 101));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setBackground(new java.awt.Color(38, 18, 137));
        jButton15.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Facturas");
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel42.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel42.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel41.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel44.setBackground(new java.awt.Color(34, 19, 101));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel45.setBackground(new java.awt.Color(34, 19, 101));
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setBackground(new java.awt.Color(38, 18, 137));
        jButton16.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Facturas");
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel45.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 60));
        jPanel45.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jPanel44.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        jPanel41.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 60));

        lbl25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl25.setText("Total");
        jPanel41.add(lbl25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lbl26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl26.setText("Subtotal");
        jPanel41.add(lbl26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl27.setText("IVA");
        jPanel41.add(lbl27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jPanel20.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 130, 120));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 130, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 635));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnVolverClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverClientesActionPerformed
        Facturas abrir= new Facturas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaVerFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaVerFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaVerFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaVerFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaVerFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraSup;
    private javax.swing.JButton btnVolverClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblCalleProveedor;
    private javax.swing.JLabel lblCiudad1;
    private javax.swing.JLabel lblCiudad10;
    private javax.swing.JLabel lblCiudad3;
    private javax.swing.JLabel lblCiudadCliente;
    private javax.swing.JLabel lblCodigoCliente;
    private javax.swing.JLabel lblColoniaProveedor;
    private javax.swing.JLabel lblEstadoCliente;
    private javax.swing.JLabel lblNumeroProveedor;
    private javax.swing.JLabel lblidEmpleado1;
    private javax.swing.JLabel lblidEmpleado2;
    private javax.swing.JLabel lblidEmpleado3;
    private javax.swing.JLabel lblidEmpleado4;
    private javax.swing.JLabel lblidEmpleado5;
    private javax.swing.JTable tblFacturas;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/iconoTedemaz.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class FondoInicioSesion extends JPanel {

        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/fondoPanelLateral.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class FondoIconoInicio extends JPanel {

        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/pruebaD/homeIcon.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class FondoUsuario extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/fotoUsuario.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }
    }


    class IconoInicio extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/InicioIcon.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class IconoProductos extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/Productos_icono_Menu.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class IconoClientes extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/Clientes_icono_Menu.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class IconoEmpleados extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/Empleados_icono_Menu.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class IconoProveedores extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/Proveedores_icono_Menu.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class IconoCaja extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/Caja_icono_Menu.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class IconoFacturas extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/Facturas_icono_Menu.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class IconoReporte extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/Reporte_icono_Menu.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

    class IconoCerrarSesion extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/vista/cerrarSesion_icon.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), rootPane);
            setOpaque(false);
            super.paint(g);
        }

    }

}
